name: Continous Deployment

on:
  push:
    branches:
      [ "main" ]
  pull_request:
    branches:
      [ "main" ]
      
jobs:
    build-and-deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js 22.2.0
              uses: actions/setup-node@v2
              with:
                node-version: '22.2.0'

            - name: Install PM2 globally
              run: npm install -g pm2

            - name: Install dependencies and build
              run: |
                cd server
                npm ci
                cd ../client
                npm ci
                npm run build
                pm2 restart server
                pm2 restart client
            - name: Reload Nginx
              run: nginx -s reload

